### ISSUE TITLE
Can Typstry be used in the same way as LaTeX for setting up plotting libraries like Makie?

### ISSUE THREAD

**Issue by kenggua211** [jakobjpeters/Typstry.jl#11]
For example, in GLMakie, use syntax like ax = Axis(f[1, 1], xlabel=L'Iter', ylabel=L'\\log (\\mathbf{r} ^ \\mathrm{T}  \\mathbf{r})') to set the parameters of Axis. 
I tried
f = Figure()
ax = Axis(f[1, 1],
    title = "Experimental data and exponential fit",
    xlabel = "Time (seconds)",
    ylabel =typst"$\e^x$",
)
but dosen't work.

**Comment by jakobjpeters** [comment]
Hi, does this [example using MakieTeX.jl](https://jakobjpeters.github.io/Typstry.jl/v0.4/guides/package_interoperability/#MakieTeX.jl) work for you? MakieTeX.jl hasn't updated to support Typstry.jl v0.4 yet though. See also this [Makie.jl discussion](https://github.com/MakieOrg/Makie.jl/discussions/4254).

**Comment by jakobjpeters** [comment]
I haven't been able to get a working example yet, but am working on seeing if it's possible. There's also another [example](https://makieorg.github.io/MakieTeX.jl/v0.4.3/formats#typst) in the MakieTeX.jl documentation.

**Comment by jakobjpeters** [comment]
Here's an answer from @asinghvi17:

> Unfortunately that isn't directly possible with MakieTeX - you can use an LTeX block as a fake ylabel though, if you rotate it by 90 degrees to the left and place it at fig[axis_layout_idx..., Left()] for example

And an example:

```julia
using Pkg: add
add(["GLMakie", "MakieTeX", "Typstry"])
f = Figure()
LTeX(f[2, 1], TypstDocument(typst"#set text(64pt); $e^x$"))
scatter(f[1:3, 2], 0, 0)
```
